# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 864)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-8, 0, 951, 701))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 931, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.codeEditor = CodeEditor(self.verticalLayoutWidget_2)
        self.codeEditor.setPlainText("")
        self.codeEditor.setObjectName("codeEditor")
        self.verticalLayout_3.addWidget(self.codeEditor)
        self.uploadButton = QtWidgets.QPushButton(self.tab)
        self.uploadButton.setGeometry(QtCore.QRect(10, 10, 311, 30))
        self.uploadButton.setObjectName("uploadButton")
        self.simulateButton = QtWidgets.QPushButton(self.tab)
        self.simulateButton.setGeometry(QtCore.QRect(370, 10, 311, 28))
        self.simulateButton.setObjectName("simulateButton")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.stepButton = QtWidgets.QPushButton(self.tab_2)
        self.stepButton.setGeometry(QtCore.QRect(120, 120, 71, 28))
        self.stepButton.setObjectName("stepButton")
        self.prevButton = QtWidgets.QPushButton(self.tab_2)
        self.prevButton.setGeometry(QtCore.QRect(200, 120, 71, 28))
        self.prevButton.setObjectName("prevButton")
        self.resetButton = QtWidgets.QPushButton(self.tab_2)
        self.resetButton.setGeometry(QtCore.QRect(280, 120, 71, 28))
        self.resetButton.setObjectName("resetButton")
        self.runButton = QtWidgets.QPushButton(self.tab_2)
        self.runButton.setGeometry(QtCore.QRect(40, 120, 71, 28))
        self.runButton.setObjectName("runButton")
        self.codeTable = QtWidgets.QTableWidget(self.tab_2)
        self.codeTable.setGeometry(QtCore.QRect(40, 170, 471, 471))
        self.codeTable.setObjectName("codeTable")
        self.codeTable.setColumnCount(4)
        self.codeTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.codeTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.codeTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.codeTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.codeTable.setHorizontalHeaderItem(3, item)
        self.codeTable.horizontalHeader().setCascadingSectionResizes(False)
        self.codeTable.horizontalHeader().setHighlightSections(True)
        self.codeTable.horizontalHeader().setSortIndicatorShown(False)
        self.codeTable.horizontalHeader().setStretchLastSection(False)
        self.codeTable.verticalHeader().setDefaultSectionSize(30)
        self.codeTable.verticalHeader().setStretchLastSection(False)
        self.registerMemoryTab = QtWidgets.QTabWidget(self.tab_2)
        self.registerMemoryTab.setGeometry(QtCore.QRect(560, 170, 381, 471))
        self.registerMemoryTab.setObjectName("registerMemoryTab")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.registerTable = QtWidgets.QTableWidget(self.tab_4)
        self.registerTable.setGeometry(QtCore.QRect(-5, -9, 381, 451))
        self.registerTable.setObjectName("registerTable")
        self.registerTable.setColumnCount(2)
        self.registerTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.registerTable.setHorizontalHeaderItem(1, item)
        self.registerMemoryTab.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.memoryTable = QtWidgets.QTableWidget(self.tab_5)
        self.memoryTable.setGeometry(QtCore.QRect(-5, -9, 381, 421))
        self.memoryTable.setObjectName("memoryTable")
        self.memoryTable.setColumnCount(5)
        self.memoryTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.memoryTable.setHorizontalHeaderItem(4, item)
        self.memoryUp = QtWidgets.QPushButton(self.tab_5)
        self.memoryUp.setGeometry(QtCore.QRect(130, 410, 93, 28))
        self.memoryUp.setObjectName("memoryUp")
        self.memoryDown = QtWidgets.QPushButton(self.tab_5)
        self.memoryDown.setGeometry(QtCore.QRect(230, 410, 93, 28))
        self.memoryDown.setObjectName("memoryDown")
        self.memoryJumpDropdown = QtWidgets.QComboBox(self.tab_5)
        self.memoryJumpDropdown.setGeometry(QtCore.QRect(10, 410, 73, 22))
        self.memoryJumpDropdown.setObjectName("memoryJumpDropdown")
        self.memoryJumpDropdown.addItem("")
        self.memoryJumpDropdown.addItem("")
        self.memoryJumpDropdown.addItem("")
        self.memoryJumpDropdown.addItem("")
        self.registerMemoryTab.addTab(self.tab_5, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.registerMemoryTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.uploadButton.setText(_translate("MainWindow", "Upload Code"))
        self.simulateButton.setText(_translate("MainWindow", "Simulate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Editor"))
        self.stepButton.setText(_translate("MainWindow", "Step"))
        self.prevButton.setText(_translate("MainWindow", "Prev"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        item = self.codeTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Machine Code"))
        item = self.codeTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.codeTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Original Code"))
        item = self.registerTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Register"))
        item = self.registerTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.registerMemoryTab.setTabText(self.registerMemoryTab.indexOf(self.tab_4), _translate("MainWindow", "Registers"))
        item = self.memoryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Address"))
        item = self.memoryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Column"))
        item = self.memoryTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "+0"))
        item = self.memoryTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "+1"))
        item = self.memoryTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "+3"))
        self.memoryUp.setText(_translate("MainWindow", "Up"))
        self.memoryDown.setText(_translate("MainWindow", "Down"))
        self.memoryJumpDropdown.setItemText(0, _translate("MainWindow", "Text"))
        self.memoryJumpDropdown.setItemText(1, _translate("MainWindow", "Data"))
        self.memoryJumpDropdown.setItemText(2, _translate("MainWindow", "Heap"))
        self.memoryJumpDropdown.setItemText(3, _translate("MainWindow", "Stack"))
        self.registerMemoryTab.setTabText(self.registerMemoryTab.indexOf(self.tab_5), _translate("MainWindow", "Memory"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Simulator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Our team"))

from codeeditor import CodeEditor

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
